### ISSUE TITLE
Update tarball for 0.1.2 release

### ISSUE THREAD

**Issue by mrstegeman** [roderm/nanoleaf-adapter#10]
I'm moving add-on packages back out of S3 and figured out that what we had for this release is different than what's attached to your release. If I remember correctly, we had to do some surgery on the tarball to get it passing CI checks. It lives here:

https://s3-us-west-2.amazonaws.com/mozilla-gateway-addons/nanoleaf-adapter-0.1.2.tgz

**Comment by mrstegeman** [comment]
Alternatively, a new release would be fine as well.

**Comment by roderm** [comment]
the `package.sh` also needed an update. 
The workflow now works and a new release is on github.
Will you upload the tgz to amazon or will it stay on github?

**Comment by mrstegeman** [comment]
I don't see any changes to `package.sh`, but there are apparently still some issues with it. See the failure here: https://github.com/WebThingsIO/addon-list/pull/1120/checks?check_run_id=1305864352

To answer your question, we'll be pulling the tarballs from GitHub now, rather than AWS.

**Comment by roderm** [comment]
@mrstegeman missed pushing master.
Please check this commit: https://github.com/roderm/nanoleaf-adapter/commit/0f58bf04f2346763b252c51fa82550ca79e298d8
I copied the `package.sh` from here: https://github.com/mrstegeman/netgear-adapter/blob/master/package.sh

The problem seems to be the `${TARFILE}.sha256sum` / `SHA256SUMS`

**Comment by roderm** [comment]
Thanks @mrstegeman for support and keeping up the work!
